import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { AiFillFacebook } from 'react-icons/ai';
import { FcGoogle } from 'react-icons/fc';

const SignUp = () => {
  return (
    <>
      <Head>
        <title>Lendsqr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Union.png"/>
      </Head>
      <main id='signup' className='container relative mx-auto p-6 md:max-w-[1440px] md:max-h-[900px]'>
        <div className='font-serif flex flex-wrap justify-center items-center space-y-3 mf:translate-y-3 lg:space-x-[169px] lg:translate-y-[20%]'>
          <div className='flex flex-col space-y-10 md:space-y-[100px]'>
            <div className='flex space-x-2 items-center'>
              <Image src='/Union.png' width={30} height={100} alt='Logo'/>
              <Image src= '/lendsqr.png' width={100} height={100} alt='Logo'/>
            </div>
            <Image src= '/pablo-sign-in 1.png' width={600} height={337.57} alt='sign-in'/>
          </div>
          <div>
            <h1 className='font-bold text-[40px]'>Welcome!</h1>
            <p className='font-[400] text-[20px]'>Enter details to sign up</p>
            <form action="submit" className='flex flex-col space-y-[24px] mt-[60px]'>
            <input className='outline-none w-[447px] h-[50px] p-3 focus:border-lime' type="text" placeholder='First Name'/>
            <input className='outline-none w-[447px] h-[50px] p-3 focus:border-lime' type="text" placeholder='Last Name'/>
              <input className='outline-none w-[447px] h-[50px] p-3 focus:border-lime' type="email" placeholder='Email'/>
              <input className='outline-none w-[447px] h-[50px] p-3 focus:invalid:border-pink-500 focus:invalid:ring-pink-500 focus:border-lime' type="password" placeholder='Password' />
              <input className='outline-none w-[447px] h-[50px] p-3 focus:invalid:border-pink-500 focus:invalid:ring-pink-500 focus:border-lime' type="password" placeholder='Confirm Password' />
              <button className='border w-[447px] h-[48px] rounded-[8px] mt-[6px] bg-lime text-white hover:bg-[#04BDA8] duration-200 cursor-pointer font-semibold text-[14px] shadow-sm'>SIGN UP</button>
            </form>
            <p className='font-semibold text-[14px] leading-[16px] tracking-widest my-[24px]'>Already have an account? <Link className='uppercase text-lime text-[12px] hover:text-[#04BDA8] duration-200 cursor-pointer' href='/'> Log In</Link></p>
          </div>
        </div>
      </main>
    </>
  )
}

export default SignUp;