import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { AiFillFacebook } from 'react-icons/ai';
import { FcGoogle } from 'react-icons/fc';
import { signInWithPopup } from 'firebase/auth';
import { auth, googleProvider } from './utils/Firebase';
import { useAuthState } from 'react-firebase-hooks/auth';
import { useRouter } from 'next/router';



export default function Home() {

  
  const googleLogin = async () => {
    try {
        const result = await signInWithPopup( auth, googleProvider)
        console.log(result.user)
    } catch(error) {
        console.error(error)
    }
  }

  const [user, loading] = useAuthState(auth);
  const route = useRouter()

  if (user) {
    route.push('/dashboard')
  } 

 
  return (
      <>
        <Head>
          <title>Lendsqr</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/Union.png"/>
        </Head>

        <main id='login' className='container relative mx-auto p-6 md:max-w-[1440px] md:max-h-[900px]'>
          <div className='font-serif flex flex-wrap justify-center items-center space-y-3 mf:translate-y-3 lg:space-x-[169px] lg:translate-y-[20%]'>
            <div className='flex flex-col space-y-10 md:space-y-[100px]'>
              <div className='flex space-x-2 items-center'>
                <Image src='/Union.png' width={30} height={100} alt='Logo'/>
                <Image src= '/lendsqr.png' width={100} height={100} alt='Logo'/>
              </div>
              <Image src= '/pablo-sign-in 1.png' width={600} height={337.57} alt='sign-in'/>
            </div>
            <div>
              <h1 className='font-bold text-[40px]'>Welcome!</h1>
              <p className='font-[400] text-[20px]'>Enter details to login</p>
              <form action="submit" className='flex flex-col space-y-[24px] mt-[60px]'>
                <input className='outline-none h-[50px] p-3 focus:border-lime md:w-[447px]' type="email" placeholder='Email'/>
                <input className='outline-none w-[447px] h-[50px] p-3 focus:invalid:border-pink-500 focus:invalid:ring-pink-500 focus:border-lime' type="text" placeholder='Password' />
                <div>
                  <a className='uppercase text-lime font-semibold text-[12px] leading-[16px] tracking-widest hover:text-[#04BDA8] duration-200 cursor-pointer'>Forget Password?</a>
                  <p className='font-semibold text-[14px] leading-[16px] tracking-widest'>Don't have an account? <Link className='uppercase text-lime text-[12px] hover:text-[#04BDA8] duration-200 cursor-pointer' href='/sign-up'> Sign Up</Link></p>
                </div>
                <button className='border w-[447px] h-[48px] rounded-[8px] mt-[6px] bg-lime text-white hover:bg-[#04BDA8] duration-200 cursor-pointer font-semibold text-[14px] shadow-sm'>LOG IN</button>
              </form>
  
  
  
                {/* ALTERNATIVE LOGIN */}
  
              <div className='text-center my-4'>
                <hr/>
                <p className='my-1'> OR</p>
                <hr/>
              </div>
              <div className='flex flex-col space-y-[16px] mb-7'>
                <button className='flex justify-center items-center border w-[447px] h-[48px] rounded-[8px] mt-[6px] bg-lime text-white hover:bg-[#04BDA8] duration-200 cursor-pointer font-semibold text-[14px] uppercase shadow-sm' onClick={googleLogin}><span><FcGoogle fontSize={26} className='mx-2' /></span> Sign in with Google</button>
                <button className='flex justify-center items-center border w-[447px] h-[48px] rounded-[8px] mt-[6px] bg-[#04BDA8] text-white hover:bg-lime duration-200 cursor-pointer font-semibold text-[14px] uppercase shadow-sm'><span><AiFillFacebook fontSize={26} className='mx-2' fill='blue' /></span> Sign in with Facebook</button>
              </div>
            </div>
          </div>
        </main>
      </>
    )
  } 
